// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PodrziMe.Services.Database;

#nullable disable

namespace PodrziMe.Services.Migrations
{
    [DbContext(typeof(PodrziMeContext))]
    [Migration("20251124095636_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PodrziMe.Services.Database.Donacija", b =>
                {
                    b.Property<int>("DonacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonacijaId"));

                    b.Property<DateOnly?>("DatumDonacije")
                        .HasColumnType("date");

                    b.Property<int?>("DonorId")
                        .HasColumnType("int");

                    b.Property<int>("IznosDonacije")
                        .HasColumnType("int");

                    b.Property<int>("KandidatId")
                        .HasColumnType("int");

                    b.HasKey("DonacijaId")
                        .HasName("PK__Donacija__9C1ECCB4383B4F42");

                    b.HasIndex(new[] { "DonorId" }, "IX_Donacija_DonorId");

                    b.HasIndex(new[] { "KandidatId" }, "IX_Donacija_KandidatId");

                    b.ToTable("Donacija", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Donor", b =>
                {
                    b.Property<int>("DonorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonorId"));

                    b.Property<DateOnly?>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UkupnoDonacija")
                        .HasColumnType("int");

                    b.Property<string>("Zanimanje")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DonorId")
                        .HasName("PK__Donor__052E3F7881996CD1");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Donor", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Kandidat", b =>
                {
                    b.Property<int>("KandidatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KandidatId"));

                    b.Property<int?>("BrojTelefona")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Odobren")
                        .HasColumnType("bit");

                    b.Property<string>("Omeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SlikaThumb")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("TakmicarProfilId")
                        .HasColumnType("int");

                    b.Property<string>("Uspjesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZeljenaDonacija")
                        .HasColumnType("int");

                    b.HasKey("KandidatId")
                        .HasName("PK__Kandidat__5F7D602BB9E73872");

                    b.HasIndex("TakmicarProfilId");

                    b.HasIndex(new[] { "KategorijaId" }, "IX_Kandidat_KategorijaId");

                    b.ToTable("Kandidat", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Kategorija", b =>
                {
                    b.Property<int>("KategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorijaId"));

                    b.Property<string>("NazivKategorije")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PodKategorijaId")
                        .HasColumnType("int");

                    b.HasKey("KategorijaId")
                        .HasName("PK__Kategori__6C3B8FEE0BC1D5A7");

                    b.HasIndex(new[] { "PodKategorijaId" }, "IX_Kategorija_PodKategorijaId");

                    b.ToTable("Kategorija", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Komentar", b =>
                {
                    b.Property<int>("KomentarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KomentarId"));

                    b.Property<string>("Komentar1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Komentar");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("UspjesnaPricaId")
                        .HasColumnType("int");

                    b.HasKey("KomentarId")
                        .HasName("PK__Komentar__C0C3049CAD6F3E08");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("UspjesnaPricaId");

                    b.ToTable("Komentar", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikId")
                        .HasName("PK__Korisnik__80B06D4132BAFC0E");

                    b.HasIndex(new[] { "UlogaId" }, "IX_Korisnik_UlogaId");

                    b.HasIndex(new[] { "KorisnickoIme" }, "UQ_Korisnik_KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Obavijest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DonacijaId")
                        .HasColumnType("int");

                    b.Property<int>("KandidatId")
                        .HasColumnType("int");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Obavijes__3214EC079C03D296");

                    b.HasIndex("DonacijaId");

                    b.HasIndex("KandidatId");

                    b.ToTable("Obavijest", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.PodKategorija", b =>
                {
                    b.Property<int>("PodKategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PodKategorijaId"));

                    b.Property<string>("NazivPodKategorije")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PodKategorijaId")
                        .HasName("PK__PodKateg__D8D5C125B165C694");

                    b.ToTable("PodKategorija", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.TakmicarProfil", b =>
                {
                    b.Property<int>("TakmicarProfilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TakmicarProfilId"));

                    b.Property<DateOnly>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TakmicarProfilId")
                        .HasName("PK__Takmicar__E312D62A7B519C4A");

                    b.HasIndex("KorisnikId");

                    b.ToTable("TakmicarProfil", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Uloga", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogaId"));

                    b.Property<string>("NazivUloge")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UlogaId")
                        .HasName("PK__Uloga__DCAB23CB44AA88F0");

                    b.ToTable("Uloga", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.UspjesnaPrica", b =>
                {
                    b.Property<int>("UspjesnaPricaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UspjesnaPricaId"));

                    b.Property<int?>("KandidatId")
                        .HasColumnType("int");

                    b.Property<string>("NaslovPrice")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Prica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("UkupnaDonacija")
                        .HasColumnType("int");

                    b.HasKey("UspjesnaPricaId")
                        .HasName("PK__Uspjesna__D62E59A5DE208AAB");

                    b.HasIndex(new[] { "KandidatId" }, "IX_UspjesnaPrica_KandidatId");

                    b.ToTable("UspjesnaPrica", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Donacija", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.Donor", "Donor")
                        .WithMany("Donacijas")
                        .HasForeignKey("DonorId")
                        .HasConstraintName("FK_Donor");

                    b.HasOne("PodrziMe.Services.Database.Kandidat", "Kandidat")
                        .WithMany("Donacijas")
                        .HasForeignKey("KandidatId")
                        .IsRequired()
                        .HasConstraintName("FK_KandidatDonacija");

                    b.Navigation("Donor");

                    b.Navigation("Kandidat");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Donor", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.Korisnik", "Korisnik")
                        .WithMany("Donors")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK_Donor_Korisnik");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Kandidat", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.Kategorija", "Kategorija")
                        .WithMany("Kandidats")
                        .HasForeignKey("KategorijaId")
                        .HasConstraintName("FK_Kategorija");

                    b.HasOne("PodrziMe.Services.Database.TakmicarProfil", "TakmicarProfil")
                        .WithMany("Kandidats")
                        .HasForeignKey("TakmicarProfilId")
                        .HasConstraintName("FK_Kandidat_TakmicarProfil");

                    b.Navigation("Kategorija");

                    b.Navigation("TakmicarProfil");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Kategorija", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.PodKategorija", "PodKategorija")
                        .WithMany("Kategorijas")
                        .HasForeignKey("PodKategorijaId")
                        .HasConstraintName("FK_PodKategorija");

                    b.Navigation("PodKategorija");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Komentar", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.Korisnik", "Korisnik")
                        .WithMany("Komentars")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK_Komentar_Korisnik");

                    b.HasOne("PodrziMe.Services.Database.UspjesnaPrica", "UspjesnaPrica")
                        .WithMany("Komentars")
                        .HasForeignKey("UspjesnaPricaId")
                        .IsRequired()
                        .HasConstraintName("FK_Komentar_UspjesnaPrica");

                    b.Navigation("Korisnik");

                    b.Navigation("UspjesnaPrica");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Korisnik", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.Uloga", "Uloga")
                        .WithMany("Korisniks")
                        .HasForeignKey("UlogaId")
                        .HasConstraintName("FK__Korisnik__UlogaI__6383C8BA");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Obavijest", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.Donacija", null)
                        .WithMany("Obavijests")
                        .HasForeignKey("DonacijaId");

                    b.HasOne("PodrziMe.Services.Database.Kandidat", "Kandidat")
                        .WithMany("Obavijests")
                        .HasForeignKey("KandidatId")
                        .IsRequired()
                        .HasConstraintName("FK_Obavijest_Kandidat");

                    b.Navigation("Kandidat");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.TakmicarProfil", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.Korisnik", "Korisnik")
                        .WithMany("TakmicarProfils")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK__TakmicarP__Koris__6FE99F9F");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.UspjesnaPrica", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.Kandidat", "Kandidat")
                        .WithMany("UspjesnaPricas")
                        .HasForeignKey("KandidatId")
                        .HasConstraintName("FK_Kandidat");

                    b.Navigation("Kandidat");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Donacija", b =>
                {
                    b.Navigation("Obavijests");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Donor", b =>
                {
                    b.Navigation("Donacijas");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Kandidat", b =>
                {
                    b.Navigation("Donacijas");

                    b.Navigation("Obavijests");

                    b.Navigation("UspjesnaPricas");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Kategorija", b =>
                {
                    b.Navigation("Kandidats");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Korisnik", b =>
                {
                    b.Navigation("Donors");

                    b.Navigation("Komentars");

                    b.Navigation("TakmicarProfils");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.PodKategorija", b =>
                {
                    b.Navigation("Kategorijas");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.TakmicarProfil", b =>
                {
                    b.Navigation("Kandidats");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Uloga", b =>
                {
                    b.Navigation("Korisniks");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.UspjesnaPrica", b =>
                {
                    b.Navigation("Komentars");
                });
#pragma warning restore 612, 618
        }
    }
}
