// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PodrziMe;
using PodrziMe.Services.Database;

#nullable disable

namespace PodrziMe.Services.Migrations
{
    [DbContext(typeof(PodrziMeContext))]
    [Migration("20250809100615_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PodrziMe.Donacija", b =>
                {
                    b.Property<int>("DonacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonacijaId"));

                    b.Property<DateOnly?>("DatumDonacije")
                        .HasColumnType("date");

                    b.Property<int?>("DonorId")
                        .HasColumnType("int");

                    b.Property<int>("IznosDonacije")
                        .HasColumnType("int");

                    b.Property<int>("KandidatId")
                        .HasColumnType("int");

                    b.HasKey("DonacijaId")
                        .HasName("PK__Donacija__9C1ECCB4383B4F42");

                    b.HasIndex("DonorId");

                    b.HasIndex("KandidatId");

                    b.ToTable("Donacija", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Donor", b =>
                {
                    b.Property<int>("DonorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonorId"));

                    b.Property<DateOnly?>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UkupnoDonacija")
                        .HasColumnType("int");

                    b.Property<string>("Zanimanje")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DonorId")
                        .HasName("PK__Donor__052E3F7881996CD1");

                    b.ToTable("Donor", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Kandidat", b =>
                {
                    b.Property<int>("KandidatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KandidatId"));

                    b.Property<int?>("BrojTelefona")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Omeni")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Uspjesi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ZeljenaDonacija")
                        .HasColumnType("int");

                    b.HasKey("KandidatId")
                        .HasName("PK__Kandidat__5F7D602BB9E73872");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Kandidat", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Kategorija", b =>
                {
                    b.Property<int>("KategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorijaId"));

                    b.Property<string>("NazivKategorije")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PodKategorijaId")
                        .HasColumnType("int");

                    b.HasKey("KategorijaId")
                        .HasName("PK__Kategori__6C3B8FEE0BC1D5A7");

                    b.HasIndex("PodKategorijaId");

                    b.ToTable("Kategorija", (string)null);
                });

            modelBuilder.Entity("PodrziMe.PodKategorija", b =>
                {
                    b.Property<int>("PodKategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PodKategorijaId"));

                    b.Property<string>("NazivPodKategorije")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PodKategorijaId")
                        .HasName("PK__PodKateg__D8D5C125B165C694");

                    b.ToTable("PodKategorija", (string)null);
                });

            modelBuilder.Entity("PodrziMe.UspjesnaPrica", b =>
                {
                    b.Property<int>("UspjesnaPricaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UspjesnaPricaId"));

                    b.Property<int?>("KandidatId")
                        .HasColumnType("int");

                    b.Property<string>("NaslovPrice")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Prica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UkupnaDonacija")
                        .HasColumnType("int");

                    b.HasKey("UspjesnaPricaId")
                        .HasName("PK__Uspjesna__D62E59A5DE208AAB");

                    b.HasIndex("KandidatId");

                    b.ToTable("UspjesnaPrica", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Donacija", b =>
                {
                    b.HasOne("PodrziMe.Donor", "Donor")
                        .WithMany("Donacijas")
                        .HasForeignKey("DonorId")
                        .HasConstraintName("FK_Donor");

                    b.HasOne("PodrziMe.Kandidat", "Kandidat")
                        .WithMany("Donacijas")
                        .HasForeignKey("KandidatId")
                        .IsRequired()
                        .HasConstraintName("FK_KandidatDonacija");

                    b.Navigation("Donor");

                    b.Navigation("Kandidat");
                });

            modelBuilder.Entity("PodrziMe.Kandidat", b =>
                {
                    b.HasOne("PodrziMe.Kategorija", "Kategorija")
                        .WithMany("Kandidats")
                        .HasForeignKey("KategorijaId")
                        .HasConstraintName("FK_Kategorija");

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("PodrziMe.Kategorija", b =>
                {
                    b.HasOne("PodrziMe.PodKategorija", "PodKategorija")
                        .WithMany("Kategorijas")
                        .HasForeignKey("PodKategorijaId")
                        .HasConstraintName("FK_PodKategorija");

                    b.Navigation("PodKategorija");
                });

            modelBuilder.Entity("PodrziMe.UspjesnaPrica", b =>
                {
                    b.HasOne("PodrziMe.Kandidat", "Kandidat")
                        .WithMany("UspjesnaPricas")
                        .HasForeignKey("KandidatId")
                        .HasConstraintName("FK_Kandidat");

                    b.Navigation("Kandidat");
                });

            modelBuilder.Entity("PodrziMe.Donor", b =>
                {
                    b.Navigation("Donacijas");
                });

            modelBuilder.Entity("PodrziMe.Kandidat", b =>
                {
                    b.Navigation("Donacijas");

                    b.Navigation("UspjesnaPricas");
                });

            modelBuilder.Entity("PodrziMe.Kategorija", b =>
                {
                    b.Navigation("Kandidats");
                });

            modelBuilder.Entity("PodrziMe.PodKategorija", b =>
                {
                    b.Navigation("Kategorijas");
                });
#pragma warning restore 612, 618
        }
    }
}
