// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PodrziMe.Services.Database;

#nullable disable

namespace PodrziMe.Services.Migrations
{
    [DbContext(typeof(PodrziMeContext))]
    partial class PodrziMeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PodrziMe.Services.Database.Donacija", b =>
                {
                    b.Property<int>("DonacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonacijaId"));

                    b.Property<DateOnly?>("DatumDonacije")
                        .HasColumnType("date");

                    b.Property<int?>("DonorId")
                        .HasColumnType("int");

                    b.Property<int>("IznosDonacije")
                        .HasColumnType("int");

                    b.Property<int>("KandidatId")
                        .HasColumnType("int");

                    b.HasKey("DonacijaId")
                        .HasName("PK__Donacija__9C1ECCB4383B4F42");

                    b.HasIndex("DonorId");

                    b.HasIndex("KandidatId");

                    b.ToTable("Donacija", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Donor", b =>
                {
                    b.Property<int>("DonorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonorId"));

                    b.Property<DateOnly?>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UkupnoDonacija")
                        .HasColumnType("int");

                    b.Property<string>("Zanimanje")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DonorId")
                        .HasName("PK__Donor__052E3F7881996CD1");

                    b.ToTable("Donor", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Kandidat", b =>
                {
                    b.Property<int>("KandidatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KandidatId"));

                    b.Property<int?>("BrojTelefona")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Omeni")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Uspjesi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ZeljenaDonacija")
                        .HasColumnType("int");

                    b.HasKey("KandidatId")
                        .HasName("PK__Kandidat__5F7D602BB9E73872");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Kandidat", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Kategorija", b =>
                {
                    b.Property<int>("KategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorijaId"));

                    b.Property<string>("NazivKategorije")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PodKategorijaId")
                        .HasColumnType("int");

                    b.HasKey("KategorijaId")
                        .HasName("PK__Kategori__6C3B8FEE0BC1D5A7");

                    b.HasIndex("PodKategorijaId");

                    b.ToTable("Kategorija", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikId")
                        .HasName("PK__Korisnik__80B06D4132BAFC0E");

                    b.HasIndex("UlogaId");

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.PodKategorija", b =>
                {
                    b.Property<int>("PodKategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PodKategorijaId"));

                    b.Property<string>("NazivPodKategorije")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PodKategorijaId")
                        .HasName("PK__PodKateg__D8D5C125B165C694");

                    b.ToTable("PodKategorija", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Uloga", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogaId"));

                    b.Property<string>("NazivUloge")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UlogaId")
                        .HasName("PK__Uloga__DCAB23CB44AA88F0");

                    b.ToTable("Uloga", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.UspjesnaPrica", b =>
                {
                    b.Property<int>("UspjesnaPricaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UspjesnaPricaId"));

                    b.Property<int?>("KandidatId")
                        .HasColumnType("int");

                    b.Property<string>("NaslovPrice")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Prica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UkupnaDonacija")
                        .HasColumnType("int");

                    b.HasKey("UspjesnaPricaId")
                        .HasName("PK__Uspjesna__D62E59A5DE208AAB");

                    b.HasIndex("KandidatId");

                    b.ToTable("UspjesnaPrica", (string)null);
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Donacija", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.Donor", "Donor")
                        .WithMany("Donacijas")
                        .HasForeignKey("DonorId")
                        .HasConstraintName("FK_Donor");

                    b.HasOne("PodrziMe.Services.Database.Kandidat", "Kandidat")
                        .WithMany("Donacijas")
                        .HasForeignKey("KandidatId")
                        .IsRequired()
                        .HasConstraintName("FK_KandidatDonacija");

                    b.Navigation("Donor");

                    b.Navigation("Kandidat");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Kandidat", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.Kategorija", "Kategorija")
                        .WithMany("Kandidats")
                        .HasForeignKey("KategorijaId")
                        .HasConstraintName("FK_Kategorija");

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Kategorija", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.PodKategorija", "PodKategorija")
                        .WithMany("Kategorijas")
                        .HasForeignKey("PodKategorijaId")
                        .HasConstraintName("FK_PodKategorija");

                    b.Navigation("PodKategorija");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Korisnik", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.Uloga", "Uloga")
                        .WithMany("Korisniks")
                        .HasForeignKey("UlogaId")
                        .HasConstraintName("FK__Korisnik__UlogaI__6383C8BA");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.UspjesnaPrica", b =>
                {
                    b.HasOne("PodrziMe.Services.Database.Kandidat", "Kandidat")
                        .WithMany("UspjesnaPricas")
                        .HasForeignKey("KandidatId")
                        .HasConstraintName("FK_Kandidat");

                    b.Navigation("Kandidat");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Donor", b =>
                {
                    b.Navigation("Donacijas");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Kandidat", b =>
                {
                    b.Navigation("Donacijas");

                    b.Navigation("UspjesnaPricas");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Kategorija", b =>
                {
                    b.Navigation("Kandidats");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.PodKategorija", b =>
                {
                    b.Navigation("Kategorijas");
                });

            modelBuilder.Entity("PodrziMe.Services.Database.Uloga", b =>
                {
                    b.Navigation("Korisniks");
                });
#pragma warning restore 612, 618
        }
    }
}
